# Generated by Django 5.0.7 on 2024-07-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='date_time',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='location',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='product',
            new_name='D',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='quantity',
            new_name='E',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='total_price',
            new_name='F',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='unit_price',
            new_name='G',
        ),
    ]
