# Generated by Django 5.0.7 on 2024-07-11 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_data', '0002_rename_date_time_data_a_rename_location_data_b_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='A',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='B',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='C',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='D',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='E',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='F',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='G',
            new_name='unit_price',
        ),
    ]
