# Generated by Django 5.0.7 on 2024-07-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_data', '0003_rename_a_data_date_time_rename_b_data_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_time',
            field=models.DateField(),
        ),
    ]
