# Generated by Django 5.0.7 on 2024-07-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_data', '0004_alter_data_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='data',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
