# Generated by Django 5.0.7 on 2024-07-11 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_data', '0005_alter_data_total_price_alter_data_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='data',
            name='unit_price',
        ),
    ]
