# Generated by Django 5.0.7 on 2024-07-12 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_data', '0007_alter_data_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_time',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='data',
            name='location',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='product',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='data',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
