# Generated by Django 5.0.7 on 2024-07-12 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_data', '0008_alter_data_date_time_alter_data_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2024, 7, 12, 12, 11, 56, 490152)),
        ),
        migrations.AlterField(
            model_name='data',
            name='quantity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
