# Generated by Django 5.0.7 on 2024-07-12 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_data', '0009_alter_data_date_time_alter_data_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_time',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 7, 12, 12, 14, 48, 432629), null=True),
        ),
    ]
