# Generated by Django 5.0.7 on 2024-07-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_data', '0010_alter_data_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
