# Generated by Django 5.0.7 on 2024-07-12 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_data', '0011_alter_data_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='date_time',
            new_name='date',
        ),
    ]
