# Generated by Django 5.0.7 on 2024-07-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_data', '0012_rename_date_time_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='total_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='unit_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
